# fly.toml app configuration file generated for pdf-exporter-blue-fog-9851 on 2026-01-12T14:54:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdf-exporter'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  FREE_MAX_CHARS = '1500'
  FREE_MAX_EXPORTS = '3'
  NODE_ENV = 'production'
  PORT = '3000'
  PRO_MAX_CHARS = '20000'
  UPGRADE_URL = 'https://pdf-exporter.com/upgrade'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
